# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{- site.title -}}, {{- site.email -}}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{- site.myvariable -}}.
title: National University of Singapore Students' Union Committee for Information Technology
title-abbreviated: NUSSU commIT
email: commit@nussu.org.sg
description: >- # this means to ignore newlines until "baseurl:"
  We are part of the National University of Singapore Students' Union (NUSSU)
  that focuses on providing quality IT services for the NUS community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nussucommit.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-redirect-from
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-paginate-v2
  # - sanitize
safe: false
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, test_suite, node_modules]

# Site configuration
# Computer centres operating hours
# Available options are:
# - default: Normal operating hours
# - exams: Exam period operating hours
# - holidays: Holiday period operating hours
# Refer to below section to change the actual hours
operating-type: holidays

###### DO NOT TOUCH BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING!!! ######
# Sponsor details
sponsor-logo: /images/acadia.png
sponsor-title: Acadia Training Pte Ltd
sponsor-link: http://acadia.sg

# Contact information
contact:
- title: General Enquiries
  phone: +65 6601 1345
  email: commit@nussu.org.sg
- title: Workshop Enquiries & Feedback
  email: trainingcell@nussucommit.com
- title: Marketing & Sponsorship Enquiries
  email: marketing@nussucommit.com

# MailChimp mailing list POST URL
# This is the URL for the form action attribute
mailchimp: "https://nussucommit.us3.list-manage.com/subscribe/post?u=26c98d6644203325fd0986041&amp;id=0a6a10fca8"

# Computer centre locations
locations:
- name: YIH Computer Centre
  shortname: YIH
  address: "Yusof Ishak House, #03-10<br>National University of Singapore<br>31 Lower Kent Ridge Road<br>Singapore 119078"
  google-maps: https://goo.gl/maps/iwKGZ6vwjXrRTNGs8.
- name: AS8 Computer Centre
  shortname: AS8
  address: "Blk AS8, #02-01<br>National University of Singapore<br>10 Kent Ridge Crescent<br>Singapore 119260"
  google-maps: https://maps.google.com/?cid=13664296870626520892

# Computer centre operating hours
# WARNING: You should be changing the "operating-type" variable above!
# The main key should match the available "operating-type", and the sub-keys
# should match the "shortname" variable in "locations."
operating-hours:
  default:
    YIH:
      hours:
      - days: "Monday - Friday"
        time: "08:30 - 21:00"
      - days: "Saturday"
        time: "08:30 - 17:00"
      - days: "Sunday"
        time: "09:30 - 15:00"
      description: "Closed on public holidays"
    AS8:
      hours:
      - days: "Monday - Friday"
        time: "08:00 - 21:00"
      - days: "Saturday"
        time: "08:00 - 19:00"
      description: "Closed on Sundays and public holidays"

  exams:
    YIH:
      hours:
      - days: "Monday - Friday"
        time: "08:30 - 21:00"
      - days: "Saturday"
        time: "08:30 - 17:00"
      - days: "Sunday"
        time: "09:30 - 15:00"
      description: "Closed on public holidays"
      smallnote: "Note: Our operating hours are extended for the exam period"
    AS8:
      hours:
      - days: "Monday - Friday"
        time: "08:00 - 21:00"
      - days: "Saturday"
        time: "08:00 - 19:00"
      - days: "Sunday"
        time: "08:00 - 17:00"
      description: "Closed on public holidays"
      smallnote: "Note: Our operating hours are extended for the exam period"

  holidays:
    YIH:
      hours:
      - days: "Monday - Friday"
        time: "08:30 - 19:00"
      - days: "Saturday"
        time: "08:30 - 15:00"
      description: "Closed on Sundays and public holidays"
      smallnote: "Note: Our operating hours are shorter due to the university vacation"
    AS8:
      hours:
      - days: "Monday - Friday"
        time: "08:00 - 19:00"
      - days: "Saturday"
        time: "08:00 - 17:00"
      description: "Closed on Sundays and public holidays"
      smallnote: "Note: Our operating hours are shorter due to the university vacation"

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights
homepage_programmes: false
homepage_resources: false
homepage_careers: false

# Custom CSS file path
custom_css_path: "/do-not-touch/theme-colors/custom.css"
custom_print_css_path: "/assets/css/print.css"

# ############################################################
# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
# pagination:

#   # Site-wide kill switch, disabled here it doesn't run at all
#   enabled: true

#   # The default document collection to paginate if nothing is specified ('posts' is default)
#   collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 12

#   # The permalink structure for the paginated pages (this can be any level deep)
#   permalink: ':num.html' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#  # Optional,omit or set both before and after to zero to disable.
#  # Controls how the pagination trail for the paginated pages look like.
#   trail:
#     before: 2
#     after: 2

#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'date'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: true

# ############################################################

# autopages:
#   enabled: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
